# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chf_website_main', '0002_businesspartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
