# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chf_website_main', '0005_auto_20170826_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='slogan',
            field=models.CharField(default='Move with the times', max_length=255),
        ),
    ]
