# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chf_website_main', '0006_siteconfiguration_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowWereDifferentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='media/%Y/%m/%d/', verbose_name='Icon')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
