# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chf_website_main', '0008_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=50, verbose_name='FA Icon Name')),
                ('link', models.URLField()),
                ('colour', models.CharField(max_length=50, verbose_name='CSS colour code')),
            ],
        ),
    ]
