# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chf_website_main', '0009_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='youtube',
        ),
    ]
