# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chf_website_main', '0010_auto_20170827_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='url',
            field=models.URLField(null=True, verbose_name='Link'),
        ),
    ]
