# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chf_website_main', '0014_auto_20170830_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='howweredifferentpoint',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
