# Generated by Django 2.0.5 on 2018-05-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chf_website_main', '0015_howweredifferentpoint_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='data_access_form',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='data_privacy_notice',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_policy',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
