version: '2'
volumes:
  data: {}
services:
  django:
    image: evilben/chf:django
    volumes:
    - static:/src/static
    - media:/src/media
    expose:
    - '8000'
    labels:
      io.rancher.container.pull_image: always
  nginx:
    image: evilben/chf:nginx
    volumes:
    - static:/src/static
    - media:/src/media
    links:
    - web-balance:web
    labels:
      io.rancher.container.pull_image: always
  web:
    image: evilben/chf:django
    volumes:
    - static:/src/static
    - media:/src/media
    expose:
    - '8000'
    labels:
      io.rancher.container.pull_image: always
  nginx-balance:
    image: rancher/lb-service-haproxy:v0.7.6
    ports:
    - 8000:8000/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  web-balance:
    image: rancher/lb-service-haproxy:v0.7.6
    expose:
    - 8000:8000/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  db:
    image: postgres:latest
